# Generated by Django 6.0.6 on 2026-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrunaudit',
            name='batch_size',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='etlrunaudit',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etlrunaudit',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etlrunaudit',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etlrunaudit',
            name='status_message',
            field=models.CharField(default='Iniciando...', max_length=255),
        ),
        migrations.AlterField(
            model_name='etlrunaudit',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DRY_RUN', 'Dry run'), ('RUNNING', 'Running')], max_length=20),
        ),
    ]
