# Generated by Django 6.0.6 on 2026-06-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubacion', '0002_etlrunaudit_batch_size_etlrunaudit_dry_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etlrunaudit',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
