"""
Django settings for etlsip project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional dependency
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv is not None:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1r9!7ke6g&a!0w0(gs8w_b!rwlo-^z-^40u_wq!^h--=7u#0dn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'incubacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etlsip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etlsip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


ETL_INCUBACION = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_SOURCE_SERVER', ''),
        'DATABASE': os.getenv('ETL_SOURCE_DATABASE', ''),
        'USERNAME': os.getenv('ETL_SOURCE_USERNAME', ''),
        'PASSWORD': os.getenv('ETL_SOURCE_PASSWORD', ''),
        'TRUSTED_CONNECTION': env_bool('ETL_SOURCE_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server'),
        'TIMEOUT': int(os.getenv('ETL_SOURCE_TIMEOUT', '30')),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_DEST_SERVER', ''),
        'DATABASE': os.getenv('ETL_DEST_DATABASE', ''),
        'USERNAME': os.getenv('ETL_DEST_USERNAME', ''),
        'PASSWORD': os.getenv('ETL_DEST_PASSWORD', ''),
        'TRUSTED_CONNECTION': env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        'TIMEOUT': int(os.getenv('ETL_DEST_TIMEOUT', '30')),
    },
    'SOURCE_TABLE': os.getenv('ETL_SOURCE_TABLE', 'mtech.mvProteinJournalTrans'),
    'DESTINATION_TABLE': os.getenv('ETL_DEST_TABLE', ''),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_DEST_DATE_COLUMN', 'xDate'),
    'SOURCE_CODES': [
        value.strip() for value in os.getenv(
            'ETL_SOURCE_CODES',
            'EOP B-HIM - Hatcher,EOP B-HIM - Allocations',
        ).split(',') if value.strip()
    ],
}


ETL_COSTO_PROD_DETALLE = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_COSTO_SOURCE_SERVER', os.getenv('ETL_SOURCE_SERVER', '')),
        'DATABASE': os.getenv('ETL_COSTO_SOURCE_DATABASE', os.getenv('ETL_SOURCE_DATABASE', '')),
        'USERNAME': os.getenv('ETL_COSTO_SOURCE_USERNAME', os.getenv('ETL_SOURCE_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_COSTO_SOURCE_PASSWORD', os.getenv('ETL_SOURCE_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_COSTO_SOURCE_TRUSTED_CONNECTION',
            env_bool('ETL_SOURCE_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_COSTO_SOURCE_DRIVER',
            os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_COSTO_SOURCE_TIMEOUT', os.getenv('ETL_SOURCE_TIMEOUT', '30'))),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_COSTO_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_COSTO_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_COSTO_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_COSTO_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_COSTO_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_COSTO_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_COSTO_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'SOURCE_TABLE': os.getenv('ETL_COSTO_SOURCE_TABLE', 'mtech.mvHimPELogEggFlowRecon'),
    'DESTINATION_TABLE': os.getenv('ETL_COSTO_DEST_TABLE', 'dbo.CostoProdDetalle'),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_COSTO_DEST_DATE_COLUMN', 'fecha_fin_mes'),
    'HATCHERIES': [
        value.strip() for value in os.getenv(
            'ETL_COSTO_HATCHERIES',
            'AVEGUAYAS,AVEPICA,INCA',
        ).split(',') if value.strip()
    ],
    'SPECIES_TYPE': int(os.getenv('ETL_COSTO_SPECIES_TYPE', '1')),
    'FARM_TYPE': int(os.getenv('ETL_COSTO_FARM_TYPE', '2')),
}


# Keycloak Configuration
KEYCLOAK_CONFIG = {
    'SERVER_URL': os.getenv('KEYCLOAK_SERVER', 'https://cdkcpro.pronaca.com/auth/'),
    'CLIENT_ID': os.getenv('KEYCLOAK_CLIENT_ID', 'sip'),
    'REALM_NAME': os.getenv('KEYCLOAK_REALM', 'pronaca-gb'),
}
USE_KEYCLOAK = env_bool('USE_KEYCLOAK', False)
