"""
Django settings for etlsip project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - optional dependency
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv is not None:
    # Load env file from project folder and workspace root.
    load_dotenv(BASE_DIR / '.env')
    load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1r9!7ke6g&a!0w0(gs8w_b!rwlo-^z-^40u_wq!^h--=7u#0dn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'incubacion',
    'reproduccion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etlsip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etlsip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DJANGO_DB_ENGINE', 'mssql'),
        'NAME': os.getenv('DJANGO_DB_NAME', os.getenv('ETL_DEST_DATABASE', 'HtcZoo')),
        'HOST': os.getenv('DJANGO_DB_HOST', os.getenv('ETL_DEST_SERVER', '')),
        'PORT': os.getenv('DJANGO_DB_PORT', ''),
        'USER': os.getenv('DJANGO_DB_USER', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'OPTIONS': {
            'driver': os.getenv('DJANGO_DB_DRIVER', os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server')),
            'extra_params': os.getenv('DJANGO_DB_EXTRA_PARAMS', 'TrustServerCertificate=yes'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'


def env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


def _build_db_extra_params(trusted_connection: bool, explicit_params: str) -> str:
    params = []
    if trusted_connection:
        params.append('Trusted_Connection=yes')
    if explicit_params:
        params.append(explicit_params.strip())
    return ';'.join(params)


DJANGO_DB_TRUSTED_CONNECTION = env_bool('DJANGO_DB_TRUSTED_CONNECTION', True)
DJANGO_DB_EXTRA_PARAMS = _build_db_extra_params(
    trusted_connection=DJANGO_DB_TRUSTED_CONNECTION,
    explicit_params=os.getenv('DJANGO_DB_EXTRA_PARAMS', 'TrustServerCertificate=yes'),
)

DATABASES['default']['OPTIONS']['extra_params'] = DJANGO_DB_EXTRA_PARAMS


ETL_INCUBACION = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_SOURCE_SERVER', ''),
        'DATABASE': os.getenv('ETL_SOURCE_DATABASE', ''),
        'USERNAME': os.getenv('ETL_SOURCE_USERNAME', ''),
        'PASSWORD': os.getenv('ETL_SOURCE_PASSWORD', ''),
        'TRUSTED_CONNECTION': env_bool('ETL_SOURCE_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server'),
        'TIMEOUT': int(os.getenv('ETL_SOURCE_TIMEOUT', '30')),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_DEST_SERVER', ''),
        'DATABASE': os.getenv('ETL_DEST_DATABASE', ''),
        'USERNAME': os.getenv('ETL_DEST_USERNAME', ''),
        'PASSWORD': os.getenv('ETL_DEST_PASSWORD', ''),
        'TRUSTED_CONNECTION': env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        'TIMEOUT': int(os.getenv('ETL_DEST_TIMEOUT', '30')),
    },
    'SOURCE_TABLE': os.getenv('ETL_SOURCE_TABLE', 'mtech.mvProteinJournalTrans'),
    'DESTINATION_TABLE': os.getenv('ETL_DEST_TABLE', ''),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_DEST_DATE_COLUMN', 'xDate'),
    'SOURCE_CODES': [
        value.strip() for value in os.getenv(
            'ETL_SOURCE_CODES',
            'EOP B-HIM - Hatcher,EOP B-HIM - Allocations',
        ).split(',') if value.strip()
    ],
}


ETL_COSTO_PROD_DETALLE = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_COSTO_SOURCE_SERVER', os.getenv('ETL_SOURCE_SERVER', '')),
        'DATABASE': os.getenv('ETL_COSTO_SOURCE_DATABASE', os.getenv('ETL_SOURCE_DATABASE', '')),
        'USERNAME': os.getenv('ETL_COSTO_SOURCE_USERNAME', os.getenv('ETL_SOURCE_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_COSTO_SOURCE_PASSWORD', os.getenv('ETL_SOURCE_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_COSTO_SOURCE_TRUSTED_CONNECTION',
            env_bool('ETL_SOURCE_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_COSTO_SOURCE_DRIVER',
            os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_COSTO_SOURCE_TIMEOUT', os.getenv('ETL_SOURCE_TIMEOUT', '30'))),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_COSTO_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_COSTO_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_COSTO_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_COSTO_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_COSTO_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_COSTO_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_COSTO_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'SOURCE_TABLE': os.getenv('ETL_COSTO_SOURCE_TABLE', 'mtech.mvHimPELogEggFlowRecon'),
    'DESTINATION_TABLE': os.getenv('ETL_COSTO_DEST_TABLE', 'dbo.CostoProdDetalle'),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_COSTO_DEST_DATE_COLUMN', 'fecha_fin_mes'),
    'HATCHERIES': [
        value.strip() for value in os.getenv(
            'ETL_COSTO_HATCHERIES',
            'AVEGUAYAS,AVEPICA,INCA',
        ).split(',') if value.strip()
    ],
    'SPECIES_TYPE': int(os.getenv('ETL_COSTO_SPECIES_TYPE', '1')),
    'FARM_TYPE': int(os.getenv('ETL_COSTO_FARM_TYPE', '2')),
}


ETL_RECEPCION = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_RECEPCION_SOURCE_SERVER', os.getenv('ETL_SOURCE_SERVER', '')),
        'DATABASE': os.getenv('ETL_RECEPCION_SOURCE_DATABASE', os.getenv('ETL_SOURCE_DATABASE', '')),
        'USERNAME': os.getenv('ETL_RECEPCION_SOURCE_USERNAME', os.getenv('ETL_SOURCE_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_RECEPCION_SOURCE_PASSWORD', os.getenv('ETL_SOURCE_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_RECEPCION_SOURCE_TRUSTED_CONNECTION',
            env_bool('ETL_SOURCE_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_RECEPCION_SOURCE_DRIVER',
            os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_RECEPCION_SOURCE_TIMEOUT', os.getenv('ETL_SOURCE_TIMEOUT', '30'))),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_RECEPCION_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_RECEPCION_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_RECEPCION_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_RECEPCION_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_RECEPCION_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_RECEPCION_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_RECEPCION_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'SOURCE_TABLE': os.getenv('ETL_RECEPCION_SOURCE_TABLE', 'mtech.mvHimEggRoomReceiving'),
    'DESTINATION_TABLE': os.getenv('ETL_RECEPCION_DEST_TABLE', 'dbo.Recepcion'),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_RECEPCION_DEST_DATE_COLUMN', 'Fecha_envio'),
    'EGG_TRANS_CODE': int(os.getenv('ETL_RECEPCION_EGG_TRANS_CODE', '17')),
    'FACILITY_TYPE': int(os.getenv('ETL_RECEPCION_FACILITY_TYPE', '1')),
}


ETL_OVOSCOPIA = {
    'SOURCE': {
        'SERVER': os.getenv('ETL_OVOSCOPIA_SOURCE_SERVER', '192.168.3.26'),
        'DATABASE': os.getenv('ETL_OVOSCOPIA_SOURCE_DATABASE', 'Mtech_v7'),
        'USERNAME': os.getenv('ETL_OVOSCOPIA_SOURCE_USERNAME', os.getenv('ETL_SOURCE_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_OVOSCOPIA_SOURCE_PASSWORD', os.getenv('ETL_SOURCE_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool('ETL_OVOSCOPIA_SOURCE_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_OVOSCOPIA_SOURCE_DRIVER', os.getenv('ETL_SOURCE_DRIVER', 'ODBC Driver 17 for SQL Server')),
        'TIMEOUT': int(os.getenv('ETL_OVOSCOPIA_SOURCE_TIMEOUT', '30')),
    },
    'DESTINATION': {
        'SERVER': os.getenv('ETL_OVOSCOPIA_DEST_SERVER', '1s1-pipbdd'),
        'DATABASE': os.getenv('ETL_OVOSCOPIA_DEST_DATABASE', 'HtcZoo'),
        'USERNAME': os.getenv('ETL_OVOSCOPIA_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_OVOSCOPIA_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool('ETL_OVOSCOPIA_DEST_TRUSTED_CONNECTION', True),
        'DRIVER': os.getenv('ETL_OVOSCOPIA_DEST_DRIVER', os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server')),
        'TIMEOUT': int(os.getenv('ETL_OVOSCOPIA_DEST_TIMEOUT', '30')),
    },
    'DESTINATION_TABLE': os.getenv('ETL_OVOSCOPIA_DEST_TABLE', 'dbo.Ovoscopia'),
}


ETL_PRESUPUESTO = {
    'DESTINATION': {
        'SERVER': os.getenv('ETL_PPTO_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_PPTO_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_PPTO_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_PPTO_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_PPTO_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_PPTO_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_PPTO_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'DESTINATION_TABLE': os.getenv('ETL_PPTO_DEST_TABLE', 'dbo.ProteinJournal_Ppto'),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_PPTO_DEST_DATE_COLUMN', 'fecha_fin_mes'),
    'DESTINATION_KEY_COLUMN': os.getenv('ETL_PPTO_DEST_KEY_COLUMN', 'centro_costo'),
    'EXCEL_PATH': os.getenv('ETL_PPTO_EXCEL_PATH', str(BASE_DIR.parent / 'presupuesto incubadoras.xlsx')),
    'SHEET_ELEMENTO_COSTO': os.getenv('ETL_PPTO_SHEET_ELEMENTO_COSTO', 'elemento_costo'),
    'SHEET_PRESUPUESTO': os.getenv('ETL_PPTO_SHEET_PRESUPUESTO', 'presupuesto'),
}


ETL_PROTEIN_JOURNAL = {
    'DESTINATION': {
        'SERVER': os.getenv('ETL_PROT_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_PROT_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_PROT_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_PROT_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_PROT_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_PROT_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_PROT_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'DESTINATION_TABLE': os.getenv('ETL_PROT_DEST_TABLE', 'dbo.ProteinJournal_Staging'),
    'DESTINATION_DATE_COLUMN': os.getenv('ETL_PROT_DEST_DATE_COLUMN', 'xDate'),
    'DESTINATION_KEY_COLUMN': os.getenv('ETL_PROT_DEST_KEY_COLUMN', 'centro_costo'),
    'DESTINATION_SECONDARY_KEY_COLUMN': os.getenv('ETL_PROT_DEST_KEY2_COLUMN', 'granja_lote'),
    'EXCEL_PATH': os.getenv('ETL_PROT_EXCEL_PATH', str(BASE_DIR.parent / 'Incubesa - costo por lote.xlsx')),
    'SHEET_DATA': os.getenv('ETL_PROT_SHEET_DATA', 'incubesa'),
    'SHEET_MAPPING': os.getenv('ETL_PROT_SHEET_MAPPING', 'columnas'),
}


ETL_CARGAS = {
    'DESTINATION': {
        'SERVER': os.getenv('ETL_CARGAS_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_CARGAS_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_CARGAS_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_CARGAS_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_CARGAS_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_CARGAS_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_CARGAS_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'DESTINATION_TABLE': os.getenv('ETL_CARGAS_DEST_TABLE', 'dbo.cargas'),
    'EXCEL_PATH': os.getenv('ETL_CARGAS_EXCEL_PATH', str(BASE_DIR.parent / 'cargas.xlsx')),
    'SHEET_DATA': os.getenv('ETL_CARGAS_SHEET_DATA', 'Hoja1'),
}


ETL_VENTA_POLLITO = {
    'DESTINATION': {
        'SERVER': os.getenv('ETL_VENTA_POLLITO_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_VENTA_POLLITO_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_VENTA_POLLITO_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_VENTA_POLLITO_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_VENTA_POLLITO_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_VENTA_POLLITO_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_VENTA_POLLITO_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'DESTINATION_TABLE': os.getenv('ETL_VENTA_POLLITO_DEST_TABLE', 'dbo.VentaPollito'),
    'EXCEL_PATH': os.getenv('ETL_VENTA_POLLITO_EXCEL_PATH', str(BASE_DIR.parent / 'data' / 'excelfiles' / 'venta-pollito.xlsx')),
    'SHEET_DATA': os.getenv('ETL_VENTA_POLLITO_SHEET_DATA', 'Hoja1'),
}


ETL_BAJA_POLLITO = {
    'DESTINATION': {
        'SERVER': os.getenv('ETL_BAJA_POLLITO_DEST_SERVER', os.getenv('ETL_DEST_SERVER', '')),
        'DATABASE': os.getenv('ETL_BAJA_POLLITO_DEST_DATABASE', os.getenv('ETL_DEST_DATABASE', '')),
        'USERNAME': os.getenv('ETL_BAJA_POLLITO_DEST_USERNAME', os.getenv('ETL_DEST_USERNAME', '')),
        'PASSWORD': os.getenv('ETL_BAJA_POLLITO_DEST_PASSWORD', os.getenv('ETL_DEST_PASSWORD', '')),
        'TRUSTED_CONNECTION': env_bool(
            'ETL_BAJA_POLLITO_DEST_TRUSTED_CONNECTION',
            env_bool('ETL_DEST_TRUSTED_CONNECTION', True),
        ),
        'DRIVER': os.getenv(
            'ETL_BAJA_POLLITO_DEST_DRIVER',
            os.getenv('ETL_DEST_DRIVER', 'ODBC Driver 17 for SQL Server'),
        ),
        'TIMEOUT': int(os.getenv('ETL_BAJA_POLLITO_DEST_TIMEOUT', os.getenv('ETL_DEST_TIMEOUT', '30'))),
    },
    'DESTINATION_TABLE': os.getenv('ETL_BAJA_POLLITO_DEST_TABLE', 'dbo.VentaPollito'),
    'EXCEL_PATH': os.getenv('ETL_BAJA_POLLITO_EXCEL_PATH', str(BASE_DIR.parent / 'data' / 'excelfiles' / 'Baja_pollito.xlsx')),
    'SHEET_DATA': os.getenv('ETL_BAJA_POLLITO_SHEET_DATA', 'exportar'),
}


# Keycloak Configuration
KEYCLOAK_CONFIG = {
    'SERVER_URL': os.getenv('KEYCLOAK_SERVER', 'https://cdkcpro.pronaca.com/auth/'),
    'CLIENT_ID': os.getenv('KEYCLOAK_CLIENT_ID', 'sip'),
    'REALM_NAME': os.getenv('KEYCLOAK_REALM', 'pronaca-gb'),
}
USE_KEYCLOAK = False
